# Generated by Django 3.2.19 on 2023-06-10 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipy',
            name='cooking_time',
            field=models.IntegerField(help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'Время готовки не может быть меньше 1!'), django.core.validators.MaxValueValidator(720, 'Время готовки более 12.0 часов? Помилуйте!')], verbose_name='Время приготовления рецепта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Слаг тега'),
        ),
    ]
