# Generated by Django 2.2.16 on 2023-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipy',
            name='cooking_time',
            field=models.DurationField(help_text='Введите время приготовления в минутах', verbose_name='Время приготовления рецепта'),
        ),
        migrations.AlterField(
            model_name='recipy',
            name='text',
            field=models.TextField(help_text='Введите описание блюда и методов приготовления', verbose_name='Текст рецепта'),
        ),
    ]
