# Generated by Django 3.2.19 on 2023-06-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230610_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='recipy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipyingredient', to='recipes.recipy', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=50, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='recipytags',
            name='recipy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipy', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipytags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.tag', verbose_name='Тег'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipy'), name='unique_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipy'), name='unique_in_shopping_cart'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'color'), name='unique_Tag'),
        ),
    ]
