# Generated by Django 3.2.19 on 2023-06-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_dosage_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dosage',
            name='unique_Dosage',
        ),
    ]
