# Generated by Django 3.2.19 on 2023-06-03 11:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20230529_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ManyToManyField(related_name='recipes_favorite_related', related_query_name='recipes_favorites', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='recipy',
            name='cooking_time',
            field=models.DurationField(help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'Время готовки не может быть меньше минуты!'), django.core.validators.MaxValueValidator(720, 'Время готовки более 12 часов? Помилуйте!')], verbose_name='Время приготовления рецепта'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ManyToManyField(related_name='recipes_shoppingcart_related', related_query_name='recipes_shoppingcarts', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\#[\\w]{6}$')], verbose_name='Цвет тега'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
