# Generated by Django 3.2.19 on 2023-06-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_dosage_unique_dosage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dosage',
            name='unique_dosage',
        ),
    ]
