# Generated by Django 3.2.19 on 2023-06-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_dosage_unique_dosage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosage',
            options={'ordering': ('ingredient',), 'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецепта'},
        ),
    ]
