# Generated by Django 3.2.19 on 2023-06-23 19:32

import django.core.validators
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=users.models.LowerEmailfield(max_length=254, unique=True, verbose_name='Е-мейл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=users.models.LowerCharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w.@+-]+\\Z$')], verbose_name='Логин'),
        ),
    ]
