# Generated by Django 3.2.19 on 2023-06-24 07:26

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=users.models.LowerEmailfield(max_length=254, unique=True, verbose_name='Е-мейл'),
        ),
    ]
